# Datasets
datasets:
  train:
    name: wrapper_audio_cae
    args:
      dataset:
        name: audio_dataset_from_folders
        args:
          folders:
            Emilia_EN: ["/home/masuser/minimax-audio/dataset/Emilia/EN"]
          sample_rate: 24000
          duration: 0.38
          n_examples: 10000000
          shuffle: true
          mono: true
      sample_rate: 24000
      duration: 0.38
      mono: true
      normalize: true
      return_coords: true
    loader:
      batch_size: 64
      num_workers: 8
      drop_last: true
      
  val:
    name: wrapper_audio_cae
    args:
      dataset:
        name: audio_dataset_from_folders
        args:
          folders:
            Emilia_EN: ["/home/masuser/minimax-audio/dataset/libritts"]
          sample_rate: 24000
          duration: 5.0
          n_examples: 100
          shuffle: false
          mono: true
      sample_rate: 24000
      duration: 5.0
      mono: true
      normalize: true
      return_coords: true
    loader:
      batch_size: 4
      num_workers: 8
      drop_last: false
      
  eval_ae:
    name: wrapper_audio_cae
    args:
      dataset:
        name: audio_dataset_from_folders
        args:
          folders:
            Emilia_EN: ["/home/masuser/minimax-audio/dataset/libritts"]
          sample_rate: 24000
          duration: 10.0
          n_examples: 1000
          shuffle: false
          mono: true
      sample_rate: 24000
      duration: 10.0
      mono: true
      normalize: true
      return_coords: true
    loader:
      batch_size: 1
      num_workers: 8
      drop_last: false

# Visualization
visualize_ae_dir: /mnt/nvme/dito_audio
visualize_ae_random_n_samples: 32
eval_ae_max_samples: 100
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]

# Enable autoencoder evaluation
evaluate_ae: true