# Datasets
datasets:
  train:
    name: wrapper_audio_cae
    args:
      dataset:
        name: class_folder_audio
        args:
          root_path: "/home/masuser/minimax-audio/dataset/Emilia/EN"
          sample_rate: 24000
          duration: 0.38
          shuffle: true
          num_channels: 1
      sample_rate: 24000
      duration: 0.38
      mono: true
      normalize: true
    loader:
      batch_size: 52
      num_workers: 8
      drop_last: true
      
  val:
    name: wrapper_audio_cae
    args:
      dataset:
        name: class_folder_audio
        args:
          root_path: "/home/masuser/minimax-audio/dataset/libritts"
          sample_rate: 24000
          duration: 5.0
          shuffle: false
          num_channels: 1
      sample_rate: 24000
      duration: 5.0
      mono: true
      normalize: true
    loader:
      batch_size: 4
      num_workers: 8
      drop_last: false
      
  eval_ae:
    name: wrapper_audio_cae
    args:
      dataset:
        name: class_folder_audio
        args:
          root_path: "/home/masuser/minimax-audio/dataset/libritts"
          sample_rate: 24000
          duration: 5.0
          shuffle: false
          num_channels: 1
      sample_rate: 24000
      duration: 5.0
      mono: true
      normalize: true
    loader:
      batch_size: 1
      num_workers: 8
      drop_last: false

# Visualization
visualize_ae_dir: /mnt/nvme/dito_audio
visualize_ae_random_n_samples: 32
eval_ae_max_samples: 100
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]

# Enable autoencoder evaluation
evaluate_ae: true